"""Updated models for Venue and Artist.

Revision ID: 1b8acd26e0bd
Revises: f9f065a14bfe
Create Date: 2021-10-05 23:46:00.906108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8acd26e0bd'
down_revision = 'f9f065a14bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('looking', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('looking', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'description')
    op.drop_column('Venue', 'looking')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'looking')
    # ### end Alembic commands ###
